//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Finalnyjj_proekt1712
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дир персонала.
    /// </summary>
    // *** Start programmer edit section *** (ДирПерсонала CustomAttributes)

    // *** End programmer edit section *** (ДирПерсонала CustomAttributes)
    [AutoAltered()]
    [Caption("Директор по персоналу")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДирПерсоналаE", new string[] {
            "Код as \'Код директора\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Сотрудники.Фамилия"})]
    [MasterViewDefineAttribute("ДирПерсоналаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ДирПерсоналаL", new string[] {
            "Код as \'Код директора\'",
            "Сотрудники.Фамилия as \'Фамилия\'"})]
    public class ДирПерсонала : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private IIS.Finalnyjj_proekt1712.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ДирПерсонала CustomMembers)

        // *** End programmer edit section *** (ДирПерсонала CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ДирПерсонала.Код CustomAttributes)

        // *** End programmer edit section *** (ДирПерсонала.Код CustomAttributes)
        [NotNull()]
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ДирПерсонала.Код Get start)

                // *** End programmer edit section *** (ДирПерсонала.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ДирПерсонала.Код Get end)

                // *** End programmer edit section *** (ДирПерсонала.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирПерсонала.Код Set start)

                // *** End programmer edit section *** (ДирПерсонала.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ДирПерсонала.Код Set end)

                // *** End programmer edit section *** (ДирПерсонала.Код Set end)
            }
        }
        
        /// <summary>
        /// Дир персонала.
        /// </summary>
        // *** Start programmer edit section *** (ДирПерсонала.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ДирПерсонала.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Finalnyjj_proekt1712.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ДирПерсонала.Сотрудники Get start)

                // *** End programmer edit section *** (ДирПерсонала.Сотрудники Get start)
                IIS.Finalnyjj_proekt1712.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ДирПерсонала.Сотрудники Get end)

                // *** End programmer edit section *** (ДирПерсонала.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирПерсонала.Сотрудники Set start)

                // *** End programmer edit section *** (ДирПерсонала.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ДирПерсонала.Сотрудники Set end)

                // *** End programmer edit section *** (ДирПерсонала.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДирПерсоналаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДирПерсоналаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДирПерсоналаE", typeof(IIS.Finalnyjj_proekt1712.ДирПерсонала));
                }
            }
            
            /// <summary>
            /// "ДирПерсоналаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДирПерсоналаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДирПерсоналаL", typeof(IIS.Finalnyjj_proekt1712.ДирПерсонала));
                }
            }
        }
    }
}
