//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Finalnyjj_proekt1712
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчетный лист.
    /// </summary>
    // *** Start programmer edit section *** (РасчетныйЛист CustomAttributes)

    // *** End programmer edit section *** (РасчетныйЛист CustomAttributes)
    [AutoAltered()]
    [Caption("Расчетный лист")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетныйЛистE", new string[] {
            "НомерДок as \'Номер документа\'",
            "Дата as \'Дата составления\'",
            "Отправлено as \'Отправлено\'",
            "ИтогоНачис as \'Итого начислено\'",
            "ИтогоУдержано as \'Итого удержано\'",
            "ИтогоКПеречи as \'Итого к перечислению\'",
            "ДирПерсонала as \'Директор по персоналу\'",
            "ДирПерсонала.Код as \'Код\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "ДирПерсонала.Код",
            "Сотрудники.Фамилия"})]
    [AssociatedDetailViewAttribute("РасчетныйЛистE", "СоставРасчета", "СоставРасчетаE", true, "", "Состав расчета", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РасчетныйЛистE", "ДирПерсонала", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Код")]
    [MasterViewDefineAttribute("РасчетныйЛистE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("РасчетныйЛистL", new string[] {
            "НомерДок as \'Номер док\'",
            "Дата as \'Дата\'",
            "Отправлено as \'Отправлено\'",
            "ИтогоНачис as \'Итого начис\'",
            "ИтогоУдержано as \'Итого удержано\'",
            "ИтогоКПеречи as \'Итого к перечи\'",
            "ДирПерсонала.Код as \'Код\'",
            "Сотрудники.Фамилия as \'Фамилия\'"})]
    public class РасчетныйЛист : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерДок;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private bool fОтправлено = false;
        
        private double fИтогоНачис;
        
        private double fИтогоУдержано;
        
        private double fИтогоКПеречи;
        
        private IIS.Finalnyjj_proekt1712.ДирПерсонала fДирПерсонала;
        
        private IIS.Finalnyjj_proekt1712.Сотрудники fСотрудники;
        
        private IIS.Finalnyjj_proekt1712.DetailArrayOfСоставРасчета fСоставРасчета;
        
        // *** Start programmer edit section *** (РасчетныйЛист CustomMembers)

        // *** End programmer edit section *** (РасчетныйЛист CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.Дата CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Get start)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Get end)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Set start)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасчетныйЛист.Дата Set end)

                // *** End programmer edit section *** (РасчетныйЛист.Дата Set end)
            }
        }
        
        /// <summary>
        /// ИтогоКПеречи.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.ИтогоКПеречи CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.ИтогоКПеречи CustomAttributes)
        public virtual double ИтогоКПеречи
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоКПеречи Get start)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоКПеречи Get start)
                double result = this.fИтогоКПеречи;
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоКПеречи Get end)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоКПеречи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоКПеречи Set start)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоКПеречи Set start)
                this.fИтогоКПеречи = value;
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоКПеречи Set end)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоКПеречи Set end)
            }
        }
        
        /// <summary>
        /// ИтогоНачис.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.ИтогоНачис CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.ИтогоНачис CustomAttributes)
        public virtual double ИтогоНачис
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоНачис Get start)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоНачис Get start)
                double result = this.fИтогоНачис;
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоНачис Get end)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоНачис Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоНачис Set start)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоНачис Set start)
                this.fИтогоНачис = value;
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоНачис Set end)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоНачис Set end)
            }
        }
        
        /// <summary>
        /// ИтогоУдержано.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.ИтогоУдержано CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.ИтогоУдержано CustomAttributes)
        public virtual double ИтогоУдержано
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоУдержано Get start)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоУдержано Get start)
                double result = this.fИтогоУдержано;
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоУдержано Get end)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоУдержано Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоУдержано Set start)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоУдержано Set start)
                this.fИтогоУдержано = value;
                // *** Start programmer edit section *** (РасчетныйЛист.ИтогоУдержано Set end)

                // *** End programmer edit section *** (РасчетныйЛист.ИтогоУдержано Set end)
            }
        }
        
        /// <summary>
        /// НомерДок.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.НомерДок CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.НомерДок CustomAttributes)
        public virtual int НомерДок
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.НомерДок Get start)

                // *** End programmer edit section *** (РасчетныйЛист.НомерДок Get start)
                int result = this.fНомерДок;
                // *** Start programmer edit section *** (РасчетныйЛист.НомерДок Get end)

                // *** End programmer edit section *** (РасчетныйЛист.НомерДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.НомерДок Set start)

                // *** End programmer edit section *** (РасчетныйЛист.НомерДок Set start)
                this.fНомерДок = value;
                // *** Start programmer edit section *** (РасчетныйЛист.НомерДок Set end)

                // *** End programmer edit section *** (РасчетныйЛист.НомерДок Set end)
            }
        }
        
        /// <summary>
        /// Отправлено.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.Отправлено CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.Отправлено CustomAttributes)
        public virtual bool Отправлено
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Отправлено Get start)

                // *** End programmer edit section *** (РасчетныйЛист.Отправлено Get start)
                bool result = this.fОтправлено;
                // *** Start programmer edit section *** (РасчетныйЛист.Отправлено Get end)

                // *** End programmer edit section *** (РасчетныйЛист.Отправлено Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Отправлено Set start)

                // *** End programmer edit section *** (РасчетныйЛист.Отправлено Set start)
                this.fОтправлено = value;
                // *** Start programmer edit section *** (РасчетныйЛист.Отправлено Set end)

                // *** End programmer edit section *** (РасчетныйЛист.Отправлено Set end)
            }
        }
        
        /// <summary>
        /// Расчетный лист.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.ДирПерсонала CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.ДирПерсонала CustomAttributes)
        [PropertyStorage(new string[] {
                "ДирПерсонала"})]
        [NotNull()]
        public virtual IIS.Finalnyjj_proekt1712.ДирПерсонала ДирПерсонала
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.ДирПерсонала Get start)

                // *** End programmer edit section *** (РасчетныйЛист.ДирПерсонала Get start)
                IIS.Finalnyjj_proekt1712.ДирПерсонала result = this.fДирПерсонала;
                // *** Start programmer edit section *** (РасчетныйЛист.ДирПерсонала Get end)

                // *** End programmer edit section *** (РасчетныйЛист.ДирПерсонала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.ДирПерсонала Set start)

                // *** End programmer edit section *** (РасчетныйЛист.ДирПерсонала Set start)
                this.fДирПерсонала = value;
                // *** Start programmer edit section *** (РасчетныйЛист.ДирПерсонала Set end)

                // *** End programmer edit section *** (РасчетныйЛист.ДирПерсонала Set end)
            }
        }
        
        /// <summary>
        /// Расчетный лист.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Finalnyjj_proekt1712.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники Get start)

                // *** End programmer edit section *** (РасчетныйЛист.Сотрудники Get start)
                IIS.Finalnyjj_proekt1712.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники Get end)

                // *** End programmer edit section *** (РасчетныйЛист.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники Set start)

                // *** End programmer edit section *** (РасчетныйЛист.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (РасчетныйЛист.Сотрудники Set end)

                // *** End programmer edit section *** (РасчетныйЛист.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Расчетный лист.
        /// </summary>
        // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета CustomAttributes)

        // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета CustomAttributes)
        public virtual IIS.Finalnyjj_proekt1712.DetailArrayOfСоставРасчета СоставРасчета
        {
            get
            {
                // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета Get start)

                // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета Get start)
                if ((this.fСоставРасчета == null))
                {
                    this.fСоставРасчета = new IIS.Finalnyjj_proekt1712.DetailArrayOfСоставРасчета(this);
                }
                IIS.Finalnyjj_proekt1712.DetailArrayOfСоставРасчета result = this.fСоставРасчета;
                // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета Get end)

                // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета Set start)

                // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета Set start)
                this.fСоставРасчета = value;
                // *** Start programmer edit section *** (РасчетныйЛист.СоставРасчета Set end)

                // *** End programmer edit section *** (РасчетныйЛист.СоставРасчета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетныйЛистE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетныйЛистE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетныйЛистE", typeof(IIS.Finalnyjj_proekt1712.РасчетныйЛист));
                }
            }
            
            /// <summary>
            /// "РасчетныйЛистL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетныйЛистL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетныйЛистL", typeof(IIS.Finalnyjj_proekt1712.РасчетныйЛист));
                }
            }
        }
    }
}
