//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Finalnyjj_proekt1712
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Согласие.
    /// </summary>
    // *** Start programmer edit section *** (Согласие CustomAttributes)

    // *** End programmer edit section *** (Согласие CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СогласиеE", new string[] {
            "НомерДок as \'Номер документа\'",
            "Дата as \'Дата составления\'",
            "Подписано as \'Подписано\'",
            "Отправлено as \'Отправлено\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Фамилия\'",
            "ДирПерсонала as \'Директор по персоналу\'",
            "ДирПерсонала.Код as \'Код\'"}, Hidden=new string[] {
            "Сотрудники.Фамилия",
            "ДирПерсонала.Код"})]
    [MasterViewDefineAttribute("СогласиеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("СогласиеE", "ДирПерсонала", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Код")]
    [View("СогласиеL", new string[] {
            "НомерДок as \'Номер документа\'",
            "Дата as \'Дата составления\'",
            "Подписано as \'Подписано\'",
            "Отправлено as \'Отправлено\'",
            "Сотрудники.Фамилия as \'Фамилия\'",
            "ДирПерсонала.Код as \'Код\'"})]
    public class Согласие : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерДок;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private bool fПодписано = false;
        
        private bool fОтправлено = false;
        
        private IIS.Finalnyjj_proekt1712.Сотрудники fСотрудники;
        
        private IIS.Finalnyjj_proekt1712.ДирПерсонала fДирПерсонала;
        
        // *** Start programmer edit section *** (Согласие CustomMembers)

        // *** End programmer edit section *** (Согласие CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Дата CustomAttributes)

        // *** End programmer edit section *** (Согласие.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Дата Get start)

                // *** End programmer edit section *** (Согласие.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Согласие.Дата Get end)

                // *** End programmer edit section *** (Согласие.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Дата Set start)

                // *** End programmer edit section *** (Согласие.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Согласие.Дата Set end)

                // *** End programmer edit section *** (Согласие.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДок.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.НомерДок CustomAttributes)

        // *** End programmer edit section *** (Согласие.НомерДок CustomAttributes)
        [NotNull()]
        public virtual int НомерДок
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.НомерДок Get start)

                // *** End programmer edit section *** (Согласие.НомерДок Get start)
                int result = this.fНомерДок;
                // *** Start programmer edit section *** (Согласие.НомерДок Get end)

                // *** End programmer edit section *** (Согласие.НомерДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.НомерДок Set start)

                // *** End programmer edit section *** (Согласие.НомерДок Set start)
                this.fНомерДок = value;
                // *** Start programmer edit section *** (Согласие.НомерДок Set end)

                // *** End programmer edit section *** (Согласие.НомерДок Set end)
            }
        }
        
        /// <summary>
        /// Отправлено.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Отправлено CustomAttributes)

        // *** End programmer edit section *** (Согласие.Отправлено CustomAttributes)
        public virtual bool Отправлено
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Отправлено Get start)

                // *** End programmer edit section *** (Согласие.Отправлено Get start)
                bool result = this.fОтправлено;
                // *** Start programmer edit section *** (Согласие.Отправлено Get end)

                // *** End programmer edit section *** (Согласие.Отправлено Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Отправлено Set start)

                // *** End programmer edit section *** (Согласие.Отправлено Set start)
                this.fОтправлено = value;
                // *** Start programmer edit section *** (Согласие.Отправлено Set end)

                // *** End programmer edit section *** (Согласие.Отправлено Set end)
            }
        }
        
        /// <summary>
        /// Подписано.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Подписано CustomAttributes)

        // *** End programmer edit section *** (Согласие.Подписано CustomAttributes)
        public virtual bool Подписано
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Подписано Get start)

                // *** End programmer edit section *** (Согласие.Подписано Get start)
                bool result = this.fПодписано;
                // *** Start programmer edit section *** (Согласие.Подписано Get end)

                // *** End programmer edit section *** (Согласие.Подписано Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Подписано Set start)

                // *** End programmer edit section *** (Согласие.Подписано Set start)
                this.fПодписано = value;
                // *** Start programmer edit section *** (Согласие.Подписано Set end)

                // *** End programmer edit section *** (Согласие.Подписано Set end)
            }
        }
        
        /// <summary>
        /// Согласие.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.ДирПерсонала CustomAttributes)

        // *** End programmer edit section *** (Согласие.ДирПерсонала CustomAttributes)
        [PropertyStorage(new string[] {
                "ДирПерсонала"})]
        [NotNull()]
        public virtual IIS.Finalnyjj_proekt1712.ДирПерсонала ДирПерсонала
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.ДирПерсонала Get start)

                // *** End programmer edit section *** (Согласие.ДирПерсонала Get start)
                IIS.Finalnyjj_proekt1712.ДирПерсонала result = this.fДирПерсонала;
                // *** Start programmer edit section *** (Согласие.ДирПерсонала Get end)

                // *** End programmer edit section *** (Согласие.ДирПерсонала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.ДирПерсонала Set start)

                // *** End programmer edit section *** (Согласие.ДирПерсонала Set start)
                this.fДирПерсонала = value;
                // *** Start programmer edit section *** (Согласие.ДирПерсонала Set end)

                // *** End programmer edit section *** (Согласие.ДирПерсонала Set end)
            }
        }
        
        /// <summary>
        /// Согласие.
        /// </summary>
        // *** Start programmer edit section *** (Согласие.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Согласие.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Finalnyjj_proekt1712.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Согласие.Сотрудники Get start)

                // *** End programmer edit section *** (Согласие.Сотрудники Get start)
                IIS.Finalnyjj_proekt1712.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Согласие.Сотрудники Get end)

                // *** End programmer edit section *** (Согласие.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Согласие.Сотрудники Set start)

                // *** End programmer edit section *** (Согласие.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Согласие.Сотрудники Set end)

                // *** End programmer edit section *** (Согласие.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СогласиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СогласиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СогласиеE", typeof(IIS.Finalnyjj_proekt1712.Согласие));
                }
            }
            
            /// <summary>
            /// "СогласиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СогласиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СогласиеL", typeof(IIS.Finalnyjj_proekt1712.Согласие));
                }
            }
        }
    }
}
